version: '3.1'

services:

  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ssdev
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPW
    networks:
      - mongo-network
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mongo-network
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: rootPW
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootPW

networks:
  mongo-network:
    driver: bridge

volumes:
  dbdata:
    driver: local