version: '3.1'

services:

  secretsanta:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_secretsanta
    networks:
      - ui-test-network
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ssdev
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPW
    networks:
      - ui-test-network
    ports:
      - "27017:27017"

networks:
  ui-test-network:
    driver: bridge

volumes:
  test-data:
    driver: local
