# Build phase --------------------------------------------------------------------

FROM golang:1.19-alpine AS builder

RUN apk --no-cache add make build-base
RUN mkdir app
ADD ./ /app

WORKDIR /app

RUN apk update
RUN apk add nodejs npm
RUN apk add --no-cache make protobuf-dev

RUN make build.ci

# Main image --------------------------------------------------------------------

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/backend/_build/secretsanta ./secretsanta
CMD ["./secretsanta"]