# Build phase --------------------------------------------------------------------

FROM golang:1.16-alpine AS builder

RUN apk --no-cache add make build-base
RUN mkdir app
ADD . /app

WORKDIR /app

RUN make build.refresh

# Main image --------------------------------------------------------------------

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/backend/_build/secretsanta ./secretsanta
CMD ["./secretsanta"]